import './product.dart';

List<Product> products = [
  Product(
    title: 'Mango',
    category: 'Pullover',
    price: '51',
    rate: 3,
    favorite: false,
  ),
  Product(
    title: 'Dorothy Perkins',
    category: 'Blouse',
    price: '34',
    rate: 5,
    favorite: true,
  ),
  Product(
    title: 'LOST Ink',
    category: 'T-shirt',
    price: '12',
    rate: 2.5,
    favorite: false,
  ),
  Product(
    title: 'Top shop',
    category: 'Shirt',
    price: '42',
    rate: 4,
    favorite: true,
  ),
  Product(
    title: 'Mango',
    category: 'Pullover',
    price: '51',
    rate: 3,
    favorite: false,
  ),
  Product(
    title: 'Dorothy Perkins',
    category: 'Blouse',
    price: '34',
    rate: 5,
    favorite: true,
  ),
  Product(
    title: 'LOST Ink',
    category: 'T-shirt',
    price: '12',
    rate: 2.5,
    favorite: false,
  ),
  Product(
    title: 'Top shop',
    category: 'Shirt',
    price: '42',
    rate: 4,
    favorite: true,
  ),
  Product(
    title: 'Mango',
    category: 'Pullover',
    price: '51',
    rate: 3,
    favorite: false,
  ),
  Product(
    title: 'Dorothy Perkins',
    category: 'Blouse',
    price: '34',
    rate: 5,
    favorite: true,
  ),
  Product(
    title: 'LOST Ink',
    category: 'T-shirt',
    price: '12',
    rate: 2.5,
    favorite: false,
  ),
  Product(
    title: 'Top shop',
    category: 'Shirt',
    price: '42',
    rate: 4,
    favorite: true,
  ),
];
